### ISSUE TITLE
go-pg v10.7.4 doesn't build with Bazel

### ISSUE THREAD

**Issue by marvin-hansen** [go-pg/pg#1832]
Issue tracker is used for reporting bugs and discussing new features. Please use
[Discord](https://discord.gg/rWtp5Aj) or [stackoverflow](https://stackoverflow.com) for supporting
issues.

Go PG doesn't build with Bazel when added as external dependency. 

## Expected Behavior

Should build, like most other go repos. 

## Current Behavior

bazel build terminates with the error shown below. Apparently, the root cause relates to  a file called "Makefile.proto." which bazel tries to compile using the proto compile. The name of the file indicates it may be a make file instead and thus causes the proto compile to faill. 

## Steps to Reproduce

1. go get github.com/go-pg/pg/v10
2.  bazel run //:gazelle -- update-repos -from_file=go.mod 
3.   bazel run //:gazelle
4.  bazel build //shared/db:go_default_library

In detail, the steps above require a working Bazel & gazelle installation. 

2. Step sources dependencies from go.mod, converts it to Bazel, and adds it to WORKSPACE. - Works fine.
3. Step sources import paths from WORKSPACE, matches against imports in go files and generates BUILD files. - Works fie.
4. Step build the generated default target "go_default_library" 

## Context (Environment)

I am building go / gRPC microservices using Bazel in a mono-repo. Because GORM is not ideal in my scenario, I was looking for a simpler, faster, and more robust alternative and go-pg ticks off 9 out of 10 boxes with the last one being Bazel integration. Bazel is make or break for me.  

Environment :
Ubuntu 20.04 LTS 
Bazel 4.0 LTS
Go 1.5 

Bazel manages the entire Dev process, means Build, Test, Containerization, push to registry, and Kubernetes deployment. 

## Detailed Description

It seems the compile error is caused when bazel compile the opentelemetry-go dependency.  

## Possible Implementation

I am filling a bug with opentelemetry-go team  asking to rename the Makefile in question but that requires go-pg to update to a fixed version given the opentelemetry-go team  solves the issue. 

 

##  Log 

/io_opentelemetry_go_otel/BUILD.bazel:5:14: Generating Descriptor Set proto_library @io_opentelemetry_go_otel//:Makefile_proto failed: (Exit 1
): protoc failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc '-
-proto_path=external/io_opentelemetry_go_otel' ... (remaining 6 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox protoc failed: error executing command bazel-out/k8-op
t-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc '--proto_path=external/io_opentelemetry_go_otel' ... (remai
ning 6 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/compiler/parser.cc:646] No syntax specified f
or the proto file: Makefile.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax vers
ion. (Defaulted to proto2 syntax.)
Makefile.proto:1:1: Expected top-level statement (e.g. "message").
Makefile.proto:1:25: Expected top-level statement (e.g. "message").
Makefile.proto:5:1: Expected top-level statement (e.g. "message").
Makefile.proto:32:23: Already saw decimal point or exponent; can't have another one.
Makefile.proto:39:113: "/*" inside block comment.  Block comments cannot be nested.
Makefile.proto:39:187: "/*" inside block comment.  Block comments cannot be nested.
Makefile.proto:118:41: "/*" inside block comment.  Block comments cannot be nested.
Makefile.proto:130:1: End-of-file inside block comment.
Makefile.proto:39:208:   Comment started here.
Target //shared/db:go_default_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.499s, Critical Path: 0.12s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully

**Comment by marvin-hansen** [comment]
Tracked down the file in the  opentelemetry-go repo, opened an issue, and filled a PR.

https://github.com/open-telemetry/opentelemetry-go/issues/1525

https://github.com/open-telemetry/opentelemetry-go/pull/1526

**Comment by marvin-hansen** [comment]
The issue has been fixed in https://github.com/open-telemetry/opentelemetry-go/pull/1468 but not been released yet. 

if possible, please update to the next release of open-telemetry when it comes out as it contains the patch.

**Comment by vmihailenco** [comment]
@marvin-hansen thanks for the update - I will update Otel when there is a new version.

**Comment by marvin-hansen** [comment]
@vmihailenco

otel just released a new version, please update if possible.

Thank you


https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.17.0

**Comment by vmihailenco** [comment]
https://github.com/open-telemetry/opentelemetry-go-contrib is still not updated

**Comment by marvin-hansen** [comment]
@vmihailenco thanks for the update & merge.
Just pinned my dep to that commit and my Bazel build passes!

**Comment by vmihailenco** [comment]
Thank you! I will add a tag once otel-go-contrib is updated.
